// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/antonbabenko/terraform-provider-openai/v2/internal/sdk/models/shared"
	"net/http"
)

type ListModelsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	ListModelsResponse *shared.ListModelsResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ListModelsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListModelsResponse) GetListModelsResponse() *shared.ListModelsResponse {
	if o == nil {
		return nil
	}
	return o.ListModelsResponse
}

func (o *ListModelsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListModelsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
