// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// ChatCompletionResponseMessageFunctionCall - The name and arguments of a function that should be called, as generated by the model.
type ChatCompletionResponseMessageFunctionCall struct {
	// The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
	Arguments *string `json:"arguments,omitempty"`
	// The name of the function to call.
	Name *string `json:"name,omitempty"`
}

func (o *ChatCompletionResponseMessageFunctionCall) GetArguments() *string {
	if o == nil {
		return nil
	}
	return o.Arguments
}

func (o *ChatCompletionResponseMessageFunctionCall) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

// ChatCompletionResponseMessageRole - The role of the author of this message.
type ChatCompletionResponseMessageRole string

const (
	ChatCompletionResponseMessageRoleSystem    ChatCompletionResponseMessageRole = "system"
	ChatCompletionResponseMessageRoleUser      ChatCompletionResponseMessageRole = "user"
	ChatCompletionResponseMessageRoleAssistant ChatCompletionResponseMessageRole = "assistant"
	ChatCompletionResponseMessageRoleFunction  ChatCompletionResponseMessageRole = "function"
)

func (e ChatCompletionResponseMessageRole) ToPointer() *ChatCompletionResponseMessageRole {
	return &e
}

func (e *ChatCompletionResponseMessageRole) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "system":
		fallthrough
	case "user":
		fallthrough
	case "assistant":
		fallthrough
	case "function":
		*e = ChatCompletionResponseMessageRole(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ChatCompletionResponseMessageRole: %v", v)
	}
}

type ChatCompletionResponseMessage struct {
	// The contents of the message.
	Content *string `json:"content,omitempty"`
	// The name and arguments of a function that should be called, as generated by the model.
	FunctionCall *ChatCompletionResponseMessageFunctionCall `json:"function_call,omitempty"`
	// The role of the author of this message.
	Role ChatCompletionResponseMessageRole `json:"role"`
}

func (o *ChatCompletionResponseMessage) GetContent() *string {
	if o == nil {
		return nil
	}
	return o.Content
}

func (o *ChatCompletionResponseMessage) GetFunctionCall() *ChatCompletionResponseMessageFunctionCall {
	if o == nil {
		return nil
	}
	return o.FunctionCall
}

func (o *ChatCompletionResponseMessage) GetRole() ChatCompletionResponseMessageRole {
	if o == nil {
		return ChatCompletionResponseMessageRole("")
	}
	return o.Role
}
