// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type CreateChatCompletionResponseChoicesFinishReason string

const (
	CreateChatCompletionResponseChoicesFinishReasonStop         CreateChatCompletionResponseChoicesFinishReason = "stop"
	CreateChatCompletionResponseChoicesFinishReasonLength       CreateChatCompletionResponseChoicesFinishReason = "length"
	CreateChatCompletionResponseChoicesFinishReasonFunctionCall CreateChatCompletionResponseChoicesFinishReason = "function_call"
)

func (e CreateChatCompletionResponseChoicesFinishReason) ToPointer() *CreateChatCompletionResponseChoicesFinishReason {
	return &e
}

func (e *CreateChatCompletionResponseChoicesFinishReason) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "stop":
		fallthrough
	case "length":
		fallthrough
	case "function_call":
		*e = CreateChatCompletionResponseChoicesFinishReason(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateChatCompletionResponseChoicesFinishReason: %v", v)
	}
}

type CreateChatCompletionResponseChoices struct {
	FinishReason CreateChatCompletionResponseChoicesFinishReason `json:"finish_reason"`
	Index        int64                                           `json:"index"`
	Message      ChatCompletionResponseMessage                   `json:"message"`
}

func (o *CreateChatCompletionResponseChoices) GetFinishReason() CreateChatCompletionResponseChoicesFinishReason {
	if o == nil {
		return CreateChatCompletionResponseChoicesFinishReason("")
	}
	return o.FinishReason
}

func (o *CreateChatCompletionResponseChoices) GetIndex() int64 {
	if o == nil {
		return 0
	}
	return o.Index
}

func (o *CreateChatCompletionResponseChoices) GetMessage() ChatCompletionResponseMessage {
	if o == nil {
		return ChatCompletionResponseMessage{}
	}
	return o.Message
}

type CreateChatCompletionResponseUsage struct {
	CompletionTokens int64 `json:"completion_tokens"`
	PromptTokens     int64 `json:"prompt_tokens"`
	TotalTokens      int64 `json:"total_tokens"`
}

func (o *CreateChatCompletionResponseUsage) GetCompletionTokens() int64 {
	if o == nil {
		return 0
	}
	return o.CompletionTokens
}

func (o *CreateChatCompletionResponseUsage) GetPromptTokens() int64 {
	if o == nil {
		return 0
	}
	return o.PromptTokens
}

func (o *CreateChatCompletionResponseUsage) GetTotalTokens() int64 {
	if o == nil {
		return 0
	}
	return o.TotalTokens
}

type CreateChatCompletionResponse struct {
	Choices []CreateChatCompletionResponseChoices `json:"choices"`
	Created int64                                 `json:"created"`
	ID      string                                `json:"id"`
	Model   string                                `json:"model"`
	Object  string                                `json:"object"`
	Usage   *CreateChatCompletionResponseUsage    `json:"usage,omitempty"`
}

func (o *CreateChatCompletionResponse) GetChoices() []CreateChatCompletionResponseChoices {
	if o == nil {
		return []CreateChatCompletionResponseChoices{}
	}
	return o.Choices
}

func (o *CreateChatCompletionResponse) GetCreated() int64 {
	if o == nil {
		return 0
	}
	return o.Created
}

func (o *CreateChatCompletionResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreateChatCompletionResponse) GetModel() string {
	if o == nil {
		return ""
	}
	return o.Model
}

func (o *CreateChatCompletionResponse) GetObject() string {
	if o == nil {
		return ""
	}
	return o.Object
}

func (o *CreateChatCompletionResponse) GetUsage() *CreateChatCompletionResponseUsage {
	if o == nil {
		return nil
	}
	return o.Usage
}
