// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/antonbabenko/terraform-provider-openai/v2/internal/sdk/pkg/utils"
)

// Two - Controls how the model responds to function calls. "none" means the model does not call a function, and responds to the end-user. "auto" means the model can pick between an end-user or calling a function.  Specifying a particular function via `{"name":\ "my_function"}` forces the model to call that function. "none" is the default when no functions are present. "auto" is the default if functions are present.
type Two struct {
	// The name of the function to call.
	Name string `json:"name"`
}

func (o *Two) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

// One - Controls how the model responds to function calls. "none" means the model does not call a function, and responds to the end-user. "auto" means the model can pick between an end-user or calling a function.  Specifying a particular function via `{"name":\ "my_function"}` forces the model to call that function. "none" is the default when no functions are present. "auto" is the default if functions are present.
type One string

const (
	OneNone One = "none"
	OneAuto One = "auto"
)

func (e One) ToPointer() *One {
	return &e
}

func (e *One) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "none":
		fallthrough
	case "auto":
		*e = One(v)
		return nil
	default:
		return fmt.Errorf("invalid value for One: %v", v)
	}
}

type CreateChatCompletionRequestFunctionCallType string

const (
	CreateChatCompletionRequestFunctionCallTypeOne CreateChatCompletionRequestFunctionCallType = "1"
	CreateChatCompletionRequestFunctionCallTypeTwo CreateChatCompletionRequestFunctionCallType = "2"
)

type CreateChatCompletionRequestFunctionCall struct {
	One *One
	Two *Two

	Type CreateChatCompletionRequestFunctionCallType
}

func CreateCreateChatCompletionRequestFunctionCallOne(one One) CreateChatCompletionRequestFunctionCall {
	typ := CreateChatCompletionRequestFunctionCallTypeOne

	return CreateChatCompletionRequestFunctionCall{
		One:  &one,
		Type: typ,
	}
}

func CreateCreateChatCompletionRequestFunctionCallTwo(two Two) CreateChatCompletionRequestFunctionCall {
	typ := CreateChatCompletionRequestFunctionCallTypeTwo

	return CreateChatCompletionRequestFunctionCall{
		Two:  &two,
		Type: typ,
	}
}

func (u *CreateChatCompletionRequestFunctionCall) UnmarshalJSON(data []byte) error {

	two := new(Two)
	if err := utils.UnmarshalJSON(data, &two, "", true, true); err == nil {
		u.Two = two
		u.Type = CreateChatCompletionRequestFunctionCallTypeTwo
		return nil
	}

	one := new(One)
	if err := utils.UnmarshalJSON(data, &one, "", true, true); err == nil {
		u.One = one
		u.Type = CreateChatCompletionRequestFunctionCallTypeOne
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u CreateChatCompletionRequestFunctionCall) MarshalJSON() ([]byte, error) {
	if u.One != nil {
		return utils.MarshalJSON(u.One, "", true)
	}

	if u.Two != nil {
		return utils.MarshalJSON(u.Two, "", true)
	}

	return nil, errors.New("could not marshal union type: all fields are null")
}

// CreateChatCompletionRequestModel - ID of the model to use. See the [model endpoint compatibility](/docs/models/model-endpoint-compatibility) table for details on which models work with the Chat API.
type CreateChatCompletionRequestModel string

const (
	CreateChatCompletionRequestModelGpt4              CreateChatCompletionRequestModel = "gpt-4"
	CreateChatCompletionRequestModelGpt40314          CreateChatCompletionRequestModel = "gpt-4-0314"
	CreateChatCompletionRequestModelGpt40613          CreateChatCompletionRequestModel = "gpt-4-0613"
	CreateChatCompletionRequestModelGpt432k           CreateChatCompletionRequestModel = "gpt-4-32k"
	CreateChatCompletionRequestModelGpt432k0314       CreateChatCompletionRequestModel = "gpt-4-32k-0314"
	CreateChatCompletionRequestModelGpt432k0613       CreateChatCompletionRequestModel = "gpt-4-32k-0613"
	CreateChatCompletionRequestModelGpt35Turbo        CreateChatCompletionRequestModel = "gpt-3.5-turbo"
	CreateChatCompletionRequestModelGpt35Turbo16k     CreateChatCompletionRequestModel = "gpt-3.5-turbo-16k"
	CreateChatCompletionRequestModelGpt35Turbo0301    CreateChatCompletionRequestModel = "gpt-3.5-turbo-0301"
	CreateChatCompletionRequestModelGpt35Turbo0613    CreateChatCompletionRequestModel = "gpt-3.5-turbo-0613"
	CreateChatCompletionRequestModelGpt35Turbo16k0613 CreateChatCompletionRequestModel = "gpt-3.5-turbo-16k-0613"
)

func (e CreateChatCompletionRequestModel) ToPointer() *CreateChatCompletionRequestModel {
	return &e
}

func (e *CreateChatCompletionRequestModel) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "gpt-4":
		fallthrough
	case "gpt-4-0314":
		fallthrough
	case "gpt-4-0613":
		fallthrough
	case "gpt-4-32k":
		fallthrough
	case "gpt-4-32k-0314":
		fallthrough
	case "gpt-4-32k-0613":
		fallthrough
	case "gpt-3.5-turbo":
		fallthrough
	case "gpt-3.5-turbo-16k":
		fallthrough
	case "gpt-3.5-turbo-0301":
		fallthrough
	case "gpt-3.5-turbo-0613":
		fallthrough
	case "gpt-3.5-turbo-16k-0613":
		*e = CreateChatCompletionRequestModel(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateChatCompletionRequestModel: %v", v)
	}
}

type StopType string

const (
	StopTypeStr        StopType = "str"
	StopTypeArrayOfstr StopType = "arrayOfstr"
)

type Stop struct {
	Str        *string
	ArrayOfstr []string

	Type StopType
}

func CreateStopStr(str string) Stop {
	typ := StopTypeStr

	return Stop{
		Str:  &str,
		Type: typ,
	}
}

func CreateStopArrayOfstr(arrayOfstr []string) Stop {
	typ := StopTypeArrayOfstr

	return Stop{
		ArrayOfstr: arrayOfstr,
		Type:       typ,
	}
}

func (u *Stop) UnmarshalJSON(data []byte) error {

	str := new(string)
	if err := utils.UnmarshalJSON(data, &str, "", true, true); err == nil {
		u.Str = str
		u.Type = StopTypeStr
		return nil
	}

	arrayOfstr := []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfstr, "", true, true); err == nil {
		u.ArrayOfstr = arrayOfstr
		u.Type = StopTypeArrayOfstr
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u Stop) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfstr != nil {
		return utils.MarshalJSON(u.ArrayOfstr, "", true)
	}

	return nil, errors.New("could not marshal union type: all fields are null")
}

type CreateChatCompletionRequest struct {
	// Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim.
	//
	// [See more information about frequency and presence penalties.](/docs/api-reference/parameter-details)
	//
	FrequencyPenalty *float64 `default:"0" json:"frequency_penalty"`
	// Controls how the model responds to function calls. "none" means the model does not call a function, and responds to the end-user. "auto" means the model can pick between an end-user or calling a function.  Specifying a particular function via `{"name":\ "my_function"}` forces the model to call that function. "none" is the default when no functions are present. "auto" is the default if functions are present.
	FunctionCall *CreateChatCompletionRequestFunctionCall `json:"function_call,omitempty"`
	// A list of functions the model may generate JSON inputs for.
	Functions []ChatCompletionFunctions `json:"functions,omitempty"`
	// Modify the likelihood of specified tokens appearing in the completion.
	//
	// Accepts a json object that maps tokens (specified by their token ID in the tokenizer) to an associated bias value from -100 to 100. Mathematically, the bias is added to the logits generated by the model prior to sampling. The exact effect will vary per model, but values between -1 and 1 should decrease or increase likelihood of selection; values like -100 or 100 should result in a ban or exclusive selection of the relevant token.
	//
	LogitBias map[string]int64 `json:"logit_bias,omitempty"`
	// The maximum number of [tokens](/tokenizer) to generate in the chat completion.
	//
	// The total length of input tokens and generated tokens is limited by the model's context length. [Example Python code](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb) for counting tokens.
	//
	MaxTokens *int64 `default:"inf" json:"max_tokens"`
	// A list of messages comprising the conversation so far. [Example Python code](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_format_inputs_to_ChatGPT_models.ipynb).
	Messages []ChatCompletionRequestMessage `json:"messages"`
	// ID of the model to use. See the [model endpoint compatibility](/docs/models/model-endpoint-compatibility) table for details on which models work with the Chat API.
	Model CreateChatCompletionRequestModel `json:"model"`
	// How many chat completion choices to generate for each input message.
	N *int64 `default:"1" json:"n"`
	// Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics.
	//
	// [See more information about frequency and presence penalties.](/docs/api-reference/parameter-details)
	//
	PresencePenalty *float64 `default:"0" json:"presence_penalty"`
	// Up to 4 sequences where the API will stop generating further tokens.
	//
	Stop *Stop `json:"stop,omitempty"`
	// If set, partial message deltas will be sent, like in ChatGPT. Tokens will be sent as data-only [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format) as they become available, with the stream terminated by a `data: [DONE]` message. [Example Python code](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_stream_completions.ipynb).
	//
	Stream *bool `default:"false" json:"stream"`
	// What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.
	//
	// We generally recommend altering this or `top_p` but not both.
	//
	Temperature *float64 `default:"1" json:"temperature"`
	// An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.
	//
	// We generally recommend altering this or `temperature` but not both.
	//
	TopP *float64 `default:"1" json:"top_p"`
	// A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices/end-user-ids).
	//
	User *string `json:"user,omitempty"`
}

func (c CreateChatCompletionRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateChatCompletionRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CreateChatCompletionRequest) GetFrequencyPenalty() *float64 {
	if o == nil {
		return nil
	}
	return o.FrequencyPenalty
}

func (o *CreateChatCompletionRequest) GetFunctionCall() *CreateChatCompletionRequestFunctionCall {
	if o == nil {
		return nil
	}
	return o.FunctionCall
}

func (o *CreateChatCompletionRequest) GetFunctions() []ChatCompletionFunctions {
	if o == nil {
		return nil
	}
	return o.Functions
}

func (o *CreateChatCompletionRequest) GetLogitBias() map[string]int64 {
	if o == nil {
		return nil
	}
	return o.LogitBias
}

func (o *CreateChatCompletionRequest) GetMaxTokens() *int64 {
	if o == nil {
		return nil
	}
	return o.MaxTokens
}

func (o *CreateChatCompletionRequest) GetMessages() []ChatCompletionRequestMessage {
	if o == nil {
		return []ChatCompletionRequestMessage{}
	}
	return o.Messages
}

func (o *CreateChatCompletionRequest) GetModel() CreateChatCompletionRequestModel {
	if o == nil {
		return CreateChatCompletionRequestModel("")
	}
	return o.Model
}

func (o *CreateChatCompletionRequest) GetN() *int64 {
	if o == nil {
		return nil
	}
	return o.N
}

func (o *CreateChatCompletionRequest) GetPresencePenalty() *float64 {
	if o == nil {
		return nil
	}
	return o.PresencePenalty
}

func (o *CreateChatCompletionRequest) GetStop() *Stop {
	if o == nil {
		return nil
	}
	return o.Stop
}

func (o *CreateChatCompletionRequest) GetStream() *bool {
	if o == nil {
		return nil
	}
	return o.Stream
}

func (o *CreateChatCompletionRequest) GetTemperature() *float64 {
	if o == nil {
		return nil
	}
	return o.Temperature
}

func (o *CreateChatCompletionRequest) GetTopP() *float64 {
	if o == nil {
		return nil
	}
	return o.TopP
}

func (o *CreateChatCompletionRequest) GetUser() *string {
	if o == nil {
		return nil
	}
	return o.User
}
