// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
)

// CreateEditRequestModel2 - ID of the model to use. You can use the `text-davinci-edit-001` or `code-davinci-edit-001` model with this endpoint.
type CreateEditRequestModel2 string

const (
	CreateEditRequestModel2TextDavinciEdit001 CreateEditRequestModel2 = "text-davinci-edit-001"
	CreateEditRequestModel2CodeDavinciEdit001 CreateEditRequestModel2 = "code-davinci-edit-001"
)

func (e CreateEditRequestModel2) ToPointer() *CreateEditRequestModel2 {
	return &e
}

func (e *CreateEditRequestModel2) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "text-davinci-edit-001":
		fallthrough
	case "code-davinci-edit-001":
		*e = CreateEditRequestModel2(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateEditRequestModel2: %v", v)
	}
}

type CreateEditRequestModelType string

const (
	CreateEditRequestModelTypeStr                     CreateEditRequestModelType = "str"
	CreateEditRequestModelTypeCreateEditRequestModel2 CreateEditRequestModelType = "CreateEditRequest_model_2"
)

type CreateEditRequestModel struct {
	Str                     *string
	CreateEditRequestModel2 *CreateEditRequestModel2

	Type CreateEditRequestModelType
}

func CreateCreateEditRequestModelStr(str string) CreateEditRequestModel {
	typ := CreateEditRequestModelTypeStr

	return CreateEditRequestModel{
		Str:  &str,
		Type: typ,
	}
}

func CreateCreateEditRequestModelCreateEditRequestModel2(createEditRequestModel2 CreateEditRequestModel2) CreateEditRequestModel {
	typ := CreateEditRequestModelTypeCreateEditRequestModel2

	return CreateEditRequestModel{
		CreateEditRequestModel2: &createEditRequestModel2,
		Type:                    typ,
	}
}

func (u *CreateEditRequestModel) UnmarshalJSON(data []byte) error {
	var d *json.Decoder

	str := new(string)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&str); err == nil {
		u.Str = str
		u.Type = CreateEditRequestModelTypeStr
		return nil
	}

	createEditRequestModel2 := new(CreateEditRequestModel2)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&createEditRequestModel2); err == nil {
		u.CreateEditRequestModel2 = createEditRequestModel2
		u.Type = CreateEditRequestModelTypeCreateEditRequestModel2
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u CreateEditRequestModel) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return json.Marshal(u.Str)
	}

	if u.CreateEditRequestModel2 != nil {
		return json.Marshal(u.CreateEditRequestModel2)
	}

	return nil, nil
}

type CreateEditRequest struct {
	// The input text to use as a starting point for the edit.
	Input *string `json:"input,omitempty"`
	// The instruction that tells the model how to edit the prompt.
	Instruction string `json:"instruction"`
	// ID of the model to use. You can use the `text-davinci-edit-001` or `code-davinci-edit-001` model with this endpoint.
	Model CreateEditRequestModel `json:"model"`
	// How many edits to generate for the input and instruction.
	N *int64 `json:"n,omitempty"`
	// What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.
	//
	// We generally recommend altering this or `top_p` but not both.
	//
	Temperature *float64 `json:"temperature,omitempty"`
	// An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.
	//
	// We generally recommend altering this or `temperature` but not both.
	//
	TopP *float64 `json:"top_p,omitempty"`
}
