// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ImagesResponseData struct {
	B64JSON *string `json:"b64_json,omitempty"`
	URL     *string `json:"url,omitempty"`
}

// ImagesResponse - OK
type ImagesResponse struct {
	Created int64                `json:"created"`
	Data    []ImagesResponseData `json:"data"`
}
