// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListModelsResponse - OK
type ListModelsResponse struct {
	Data   []Model `json:"data"`
	Object string  `json:"object"`
}
