// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ListFineTuneEventsResponse - OK
type ListFineTuneEventsResponse struct {
	Data   []FineTuneEvent `json:"data"`
	Object string          `json:"object"`
}
