// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Model - OK
type Model struct {
	Created int64  `json:"created"`
	ID      string `json:"id"`
	Object  string `json:"object"`
	OwnedBy string `json:"owned_by"`
}
