// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type CreateEditResponseFinishReason string

const (
	CreateEditResponseFinishReasonStop   CreateEditResponseFinishReason = "stop"
	CreateEditResponseFinishReasonLength CreateEditResponseFinishReason = "length"
)

func (e CreateEditResponseFinishReason) ToPointer() *CreateEditResponseFinishReason {
	return &e
}
func (e *CreateEditResponseFinishReason) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "stop":
		fallthrough
	case "length":
		*e = CreateEditResponseFinishReason(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateEditResponseFinishReason: %v", v)
	}
}

type CreateEditResponseChoices struct {
	FinishReason CreateEditResponseFinishReason `json:"finish_reason"`
	Index        int64                          `json:"index"`
	Text         string                         `json:"text"`
}

func (o *CreateEditResponseChoices) GetFinishReason() CreateEditResponseFinishReason {
	if o == nil {
		return CreateEditResponseFinishReason("")
	}
	return o.FinishReason
}

func (o *CreateEditResponseChoices) GetIndex() int64 {
	if o == nil {
		return 0
	}
	return o.Index
}

func (o *CreateEditResponseChoices) GetText() string {
	if o == nil {
		return ""
	}
	return o.Text
}

type CreateEditResponseUsage struct {
	CompletionTokens int64 `json:"completion_tokens"`
	PromptTokens     int64 `json:"prompt_tokens"`
	TotalTokens      int64 `json:"total_tokens"`
}

func (o *CreateEditResponseUsage) GetCompletionTokens() int64 {
	if o == nil {
		return 0
	}
	return o.CompletionTokens
}

func (o *CreateEditResponseUsage) GetPromptTokens() int64 {
	if o == nil {
		return 0
	}
	return o.PromptTokens
}

func (o *CreateEditResponseUsage) GetTotalTokens() int64 {
	if o == nil {
		return 0
	}
	return o.TotalTokens
}

type CreateEditResponse struct {
	Choices []CreateEditResponseChoices `json:"choices"`
	Created int64                       `json:"created"`
	Object  string                      `json:"object"`
	Usage   CreateEditResponseUsage     `json:"usage"`
}

func (o *CreateEditResponse) GetChoices() []CreateEditResponseChoices {
	if o == nil {
		return []CreateEditResponseChoices{}
	}
	return o.Choices
}

func (o *CreateEditResponse) GetCreated() int64 {
	if o == nil {
		return 0
	}
	return o.Created
}

func (o *CreateEditResponse) GetObject() string {
	if o == nil {
		return ""
	}
	return o.Object
}

func (o *CreateEditResponse) GetUsage() CreateEditResponseUsage {
	if o == nil {
		return CreateEditResponseUsage{}
	}
	return o.Usage
}
