// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"github.com/antonbabenko/terraform-provider-openai/v2/internal/sdk/pkg/models/shared"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *ImageResourceModel) ToCreateSDKType() *shared.CreateImageRequest {
	n := new(int64)
	if !r.N.IsUnknown() && !r.N.IsNull() {
		*n = r.N.ValueInt64()
	} else {
		n = nil
	}
	prompt := r.Prompt.ValueString()
	responseFormat := new(shared.CreateImageRequestResponseFormat)
	if !r.ResponseFormat.IsUnknown() && !r.ResponseFormat.IsNull() {
		*responseFormat = shared.CreateImageRequestResponseFormat(r.ResponseFormat.ValueString())
	} else {
		responseFormat = nil
	}
	size := new(shared.CreateImageRequestSize)
	if !r.Size.IsUnknown() && !r.Size.IsNull() {
		*size = shared.CreateImageRequestSize(r.Size.ValueString())
	} else {
		size = nil
	}
	user := new(string)
	if !r.User.IsUnknown() && !r.User.IsNull() {
		*user = r.User.ValueString()
	} else {
		user = nil
	}
	out := shared.CreateImageRequest{
		N:              n,
		Prompt:         prompt,
		ResponseFormat: responseFormat,
		Size:           size,
		User:           user,
	}
	return &out
}

func (r *ImageResourceModel) RefreshFromCreateResponse(resp *shared.ImagesResponse) {
	r.Created = types.Int64Value(resp.Created)
	if len(r.Data) > len(resp.Data) {
		r.Data = r.Data[:len(resp.Data)]
	}
	for dataCount, dataItem := range resp.Data {
		var data1 ImagesResponseData
		if dataItem.B64JSON != nil {
			data1.B64JSON = types.StringValue(*dataItem.B64JSON)
		} else {
			data1.B64JSON = types.StringNull()
		}
		if dataItem.URL != nil {
			data1.URL = types.StringValue(*dataItem.URL)
		} else {
			data1.URL = types.StringNull()
		}
		if dataCount+1 > len(r.Data) {
			r.Data = append(r.Data, data1)
		} else {
			r.Data[dataCount].B64JSON = data1.B64JSON
			r.Data[dataCount].URL = data1.URL
		}
	}
}
