// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type CreateCompletionRequestPrompt struct {
	Str                   types.String    `tfsdk:"str"`
	ArrayOfstr            []types.String  `tfsdk:"array_ofstr"`
	ArrayOfinteger        []types.Int64   `tfsdk:"array_ofinteger"`
	ArrayOfarrayOfinteger [][]types.Int64 `tfsdk:"array_ofarray_ofinteger"`
}
