// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type FunctionCall struct {
	Arguments types.String `tfsdk:"arguments"`
	Name      types.String `tfsdk:"name"`
}
