// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type Data struct {
	Embedding []types.Number `tfsdk:"embedding"`
	Index     types.Int64    `tfsdk:"index"`
	Object    types.String   `tfsdk:"object"`
}
