// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type ChatCompletionRequestMessage struct {
	Content      types.String  `tfsdk:"content"`
	FunctionCall *FunctionCall `tfsdk:"function_call"`
	Name         types.String  `tfsdk:"name"`
	Role         types.String  `tfsdk:"role"`
}
