// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type ChatCompletionResponseMessage struct {
	Content      types.String                               `tfsdk:"content"`
	FunctionCall *ChatCompletionResponseMessageFunctionCall `tfsdk:"function_call"`
	Role         types.String                               `tfsdk:"role"`
}
