// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type CreateEmbeddingResponseUsage struct {
	PromptTokens types.Int64 `tfsdk:"prompt_tokens"`
	TotalTokens  types.Int64 `tfsdk:"total_tokens"`
}
