// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type CreateCompletionResponseChoices struct {
	FinishReason types.String `tfsdk:"finish_reason"`
	Index        types.Int64  `tfsdk:"index"`
	Logprobs     *Logprobs    `tfsdk:"logprobs"`
	Text         types.String `tfsdk:"text"`
}
