// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type FunctionCall struct {
	Arguments types.String `tfsdk:"arguments"`
	Name      types.String `tfsdk:"name"`
}
