// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type ImagesResponseData struct {
	B64JSON types.String `tfsdk:"b64_json"`
	URL     types.String `tfsdk:"url"`
}
