// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type Prompt struct {
	Str                   types.String    `tfsdk:"str" tfPlanOnly:"true"`
	ArrayOfStr            []types.String  `tfsdk:"array_of_str" tfPlanOnly:"true"`
	ArrayOfInteger        []types.Int64   `tfsdk:"array_of_integer" tfPlanOnly:"true"`
	ArrayOfArrayOfInteger [][]types.Int64 `tfsdk:"array_of_array_of_integer" tfPlanOnly:"true"`
}
