// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openai/internal/sdk/pkg/models/shared"
)

type CancelFineTuneRequest struct {
	// The ID of the fine-tune job to cancel
	//
	FineTuneID string `pathParam:"style=simple,explode=false,name=fine_tune_id"`
}

type CancelFineTuneResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	FineTune *shared.FineTune
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}
