// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"oai/internal/sdk/pkg/models/shared"
)

type CreateEmbeddingResponse struct {
	ContentType string
	// OK
	CreateEmbeddingResponse *shared.CreateEmbeddingResponse
	StatusCode              int
	RawResponse             *http.Response
}
