// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openai/internal/sdk/pkg/models/shared"
)

type CreateCompletionResponse struct {
	ContentType string
	// OK
	CreateCompletionResponse *shared.CreateCompletionResponse
	StatusCode               int
	RawResponse              *http.Response
}
