// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openai/internal/sdk/pkg/models/shared"
)

type CreateChatCompletionResponse struct {
	ContentType string
	// OK
	CreateChatCompletionResponse *shared.CreateChatCompletionResponse
	StatusCode                   int
	RawResponse                  *http.Response
}
