// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openai/internal/sdk/pkg/models/shared"
)

type DeleteFileRequest struct {
	// The ID of the file to use for this request
	FileID string `pathParam:"style=simple,explode=false,name=file_id"`
}

type DeleteFileResponse struct {
	ContentType string
	// OK
	DeleteFileResponse *shared.DeleteFileResponse
	StatusCode         int
	RawResponse        *http.Response
}
