// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openai/internal/sdk/pkg/models/shared"
)

type ListModelsResponse struct {
	ContentType string
	// OK
	ListModelsResponse *shared.ListModelsResponse
	StatusCode         int
	RawResponse        *http.Response
}
