// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openai/internal/sdk/pkg/models/shared"
)

type ListFineTunesResponse struct {
	ContentType string
	// OK
	ListFineTunesResponse *shared.ListFineTunesResponse
	StatusCode            int
	RawResponse           *http.Response
}
