// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openai/v2/internal/sdk/pkg/models/shared"
)

type ListFineTunesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	ListFineTunesResponse *shared.ListFineTunesResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ListFineTunesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListFineTunesResponse) GetListFineTunesResponse() *shared.ListFineTunesResponse {
	if o == nil {
		return nil
	}
	return o.ListFineTunesResponse
}

func (o *ListFineTunesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListFineTunesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
