// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"openai/internal/sdk/pkg/models/shared"
)

type RetrieveModelRequest struct {
	// The ID of the model to use for this request
	Model string `pathParam:"style=simple,explode=false,name=model"`
}

type RetrieveModelResponse struct {
	ContentType string
	// OK
	Model       *shared.Model
	StatusCode  int
	RawResponse *http.Response
}
